package main

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

const displayTimeFormat = "2006-01-02 15:04:05 UTC"

// formatMirrorlist renders the pacman mirrorlist for the given mirrors.
func formatMirrorlist(status *MirrorStatus, mirrors []Mirror, retrieved time.Time, opts *Options, argv []string) string {
	var b strings.Builder

	header := "# Arch Linux mirrorlist generated by Reflector #"
	centered := center(header, 80, '#')
	border := strings.Repeat("#", len(centered))
	border = border + "\n" + centered + "\n" + border + "\n\n"
	b.WriteString(border)

	var command strings.Builder
	var quoteString string

	command.WriteString("reflector")
	for _, a := range argv {
        quoteString = " " + quoteArg(a)
      	command.WriteString(quoteString)
	}

	fmt.Fprintf(&b, "# %-11s %s\n", "With:", command.String())
	fmt.Fprintf(&b, "# %-11s %s\n", "When:", time.Now().UTC().Format(displayTimeFormat))
	fmt.Fprintf(&b, "# %-11s %s\n", "From:", opts.URL)
	fmt.Fprintf(&b, "# %-11s %s\n", "Retrieved:", retrieved.UTC().Format(displayTimeFormat))
	if lastCheck := parseLastCheck(status.LastCheck); !lastCheck.IsZero() {
		fmt.Fprintf(&b, "# %-11s %s\n", "Last Check:", lastCheck.Format(displayTimeFormat))
	}
	b.WriteString("\n")

	includeCountry := opts.Sort == "country"
	country := ""
	for _, m := range mirrors {
		if includeCountry {
			ctry := m.Country + " [" + m.CountryCode + "]"
			if ctry != country {
				if country != "" {
					b.WriteString("\n")
				}
				fmt.Fprintf(&b, "# %s\n", ctry)
				country = ctry
			}
		}
		fmt.Fprintf(&b, "Server = %s$repo/os/$arch\n", m.URL)
	}
	return b.String()
}

// center pads s with the fill character so the result has the given width.
func center(s string, width int, fill byte) string {
	if len(s) >= width {
		return s
	}
	total := width - len(s)
	left := total / 2
	return strings.Repeat(string(fill), left) + s + strings.Repeat(string(fill), total-left)
}

// quoteArg wraps an argument in single quotes if it could confuse a shell.
func quoteArg(s string) string {
	if s == "" || strings.ContainsAny(s, " \t\"'") {
		return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
	}
	return s
}

func parseLastCheck(s string) time.Time {
	for _, layout := range []string{
		"2006-01-02T15:04:05Z07:00",
		"2006-01-02T15:04:05.999999999Z07:00",
	} {
		if t, err := time.Parse(layout, s); err == nil {
			return t
		}
	}
	return time.Time{}
}

// formatMirrorInfo renders the --info listing for the mirrors.
func formatMirrorInfo(mirrors []Mirror) string {
	var b strings.Builder
	keys := infoKeys(mirrors[0])
	length := 0
	for _, k := range keys {
		if len(k) > length {
			length = len(k)
		}
	}
	for _, m := range mirrors {
		fmt.Fprintf(&b, "%s$repo/os/$arch\n", m.URL)
		for _, key := range keys {
			fmt.Fprintf(&b, "%*s : %s\n", length, key, infoValue(m, key))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// infoKeys returns the mirror fields shown by --info, sorted alphabetically,
// excluding "url".
func infoKeys(m Mirror) []string {
	values := infoValues(m)
	keys := make([]string, 0, len(values))
	for k := range values {
		if k != "url" {
			keys = append(keys, k)
		}
	}
	sort.Strings(keys)
	return keys
}

func infoValues(m Mirror) map[string]string {
	lastSync := ""
	if m.LastSync != nil {
		if t, err := parseLastSync(*m.LastSync); err == nil {
			lastSync = t.UTC().Format(displayTimeFormat)
		}
	}
	return map[string]string{
		"url":            m.URL,
		"protocol":       m.Protocol,
		"last_sync":      lastSync,
		"completion_pct": fmt.Sprintf("%v", m.CompletionPct),
		"delay":          fmt.Sprintf("%v", m.Delay),
		"duration_avg":   fmt.Sprintf("%v", m.DurationAvg),
		"score":          fmt.Sprintf("%v", m.Score),
		"country":        m.Country,
		"country_code":   m.CountryCode,
		"isos":           fmt.Sprintf("%v", m.Isos),
		"ipv4":           fmt.Sprintf("%v", m.IPv4),
		"ipv6":           fmt.Sprintf("%v", m.IPv6),
		"details":        m.Details,
	}
}

func infoValue(m Mirror, key string) string {
	return infoValues(m)[key]
}

// formatCountries renders the --list-countries table.
func formatCountries(mirrors []Mirror) string {
	type entry struct {
		country, code string
		count         int
	}
	index := map[[2]string]int{}
	list := []entry{}
	for _, m := range mirrors {
		if m.Country == "" && m.CountryCode == "" {
			continue
		}
		k := [2]string{m.Country, m.CountryCode}
		if _, ok := index[k]; !ok {
			index[k] = len(list)
			list = append(list, entry{country: m.Country, code: m.CountryCode})
		}
		list[index[k]].count++
	}
	sort.Slice(list, func(i, j int) bool { return list[i].country < list[j].country })

	w0, w1, w2 := len("Country"), len("Code"), len("Count")
	for _, e := range list {
		if len(e.country) > w0 {
			w0 = len(e.country)
		}
		if len(e.code) > w1 {
			w1 = len(e.code)
		}
		if n := len(fmt.Sprintf("%d", e.count)); n > w2 {
			w2 = n
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%-*s %*s %-*s\n", w0, "Country", w1, "Code", w2, "Count")
	fmt.Fprintf(&b, "%s %s %s\n",
		strings.Repeat("-", w0), strings.Repeat("-", w1), strings.Repeat("-", w2))
	for _, e := range list {
		fmt.Fprintf(&b, "%-*s %*s %*d\n", w0, e.country, w1, e.code, w2, e.count)
	}
	return b.String()
}
