# Arch Mirrors Checker configuration file for the systemd service.
#
# Empty lines and lines beginning with "#" are ignored.  All other lines
# contain valid amc command-line options, one per line. Values may be
# quoted. All options are collected into a single argument list and command
# line arguments override them.
#
# See "amc --help" for details.

# Recommended Options

# Set the output path where the mirrorlist will be saved (--save).
--save /etc/pacman.d/mirrorlist

# Select the transfer protocol (--protocol).
--protocol https

# Select the country (--country).
# Consult the list of available countries with "amc --list-countries"
# and select the countries nearest to you or the ones that you trust. For
# example:
# --country France,Germany

# Use only the most recently synchronized mirrors (--latest).
--latest 5

# Sort the mirrors by synchronization time (--sort).
--sort age
